# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null,
  "address" varchar not null
);

create table "products" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "price" int not null,
  "description" varchar not null,
  "userId" int,
  foreign key ("userId") references "people"("id")
);

CREATE TABLE "product_categories" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "description" varchar not null,
);

CREATE TABLE orders (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "order_date" Date not null,
    "userId" int,
    foreign key ("userId") references "people"("id")
);

CREATE TABLE ordered_products(
     "id" bigint generated by default as identity(start with 1) not null primary key,
     "order_id" int not null,
     "product_id" int not null,
     foreign key ("order_id") references "orders"("id"),
     foreign key ("product_id") references "products"("id")
);

# --- !Downs

drop table "people" if exists;
drop table "products" if exists;
drop table "product_categories" if exists;
drop table "orders" if exists;
