# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null,
  "address" varchar not null
);

CREATE TABLE "product_categories" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "description" varchar not null,
);

create table "products" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "price" int not null,
  "description" varchar not null,
  "categoryId" int,
  foreign key ("categoryId") references "product_categories"("id")
);

CREATE TABLE "orders" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "order_date" varchar not null,
    "userId" int,
    foreign key ("userId") references "people"("id")
);


# --- !Downs

drop table "people" if exists;
drop table "products" if exists;
drop table "product_categories" if exists;
drop table "orders" if exists;
drop table "ordered_products" if exists;
